## The main Github Actions workflow
name: CI

on:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"
      - "**.yml"
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.head_ref || github.ref || github.run_id }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

run-name: ${{ github.ref_name }}

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: |
          echo "Hello"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "event.pr.head.sha=${{ github.event.pull_request.head.sha }}"

#  create-cache:
#    if:
#        github.event_name == 'workflow_dispatch' ||
#        github.event_name == 'pull_request'
#    name: Create Test Cache
#    uses: ./.github/workflows/create-cache.yml