## The main Github Actions workflow
name: CI

on:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"
      - "**.yml"
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.head_ref || github.ref || github.run_id }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

run-name: ${{ github.ref_name }}

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Print
        id: print
        run: echo "HELLO"

  ## Create a reusable cache for tests
  ##
  ## Runs when:
  ##   - it is a node release run
  ##   or any of:
  ##     - this workflow is called manually
  ##     - PR is opened
  ##     - PR added to merge queue
  # create-cache:
  #  if: |
  #    github.event_name == 'workflow_dispatch' ||
  #    github.event_name == 'pull_request' ||
  #    github.event_name == 'merge_group'
  #  name: Create Test Cache
  #  uses: ./.github/workflows/create-cache.yml

  
